# Generated by Django 5.2.6 on 2025-09-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Principal', max_length=40)),
                ('recipient_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(max_length=120)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20)),
                ('commune', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Chile', max_length=60)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'despacho_info',
                'ordering': ['-is_default', '-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'label'), name='uniq_dispatch_label_per_user')],
            },
        ),
    ]
